-- MySQL Script generated by MySQL Workbench
-- Wed Feb 21 21:22:15 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Mapple
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Mapple
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Mapple` DEFAULT CHARACTER SET utf8 ;
USE `Mapple` ;

-- -----------------------------------------------------
-- Table `Mapple`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mapple`.`Categoria` (
  `codCategoria` INT NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` TEXT CHARACTER SET 'big5' NULL,
  PRIMARY KEY (`codCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mapple`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mapple`.`Producto` (
  `codProducto` INT NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` TEXT NULL,
  `precioUnitario` DOUBLE NOT NULL,
  `unidadesEnStock` VARCHAR(45) NOT NULL,
  `codCategoria` INT NOT NULL,
  PRIMARY KEY (`codProducto`, `codCategoria`),
  INDEX `fk_Producto_Categoria1_idx` (`codCategoria` ASC),
  CONSTRAINT `fk_Producto_Categoria1`
    FOREIGN KEY (`codCategoria`)
    REFERENCES `Mapple`.`Categoria` (`codCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mapple`.`Pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mapple`.`Pais` (
  `codPais` INT NOT NULL,
  `nombrePais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codPais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mapple`.`Direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mapple`.`Direccion` (
  `codDireccion` INT NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(80) NOT NULL,
  `calle` VARCHAR(80) NOT NULL,
  `codPostal` VARCHAR(15) NOT NULL,
  `codPais` INT NOT NULL,
  PRIMARY KEY (`codDireccion`, `codPais`),
  INDEX `fk_Direccion_Pais1_idx` (`codPais` ASC),
  CONSTRAINT `fk_Direccion_Pais1`
    FOREIGN KEY (`codPais`)
    REFERENCES `Mapple`.`Pais` (`codPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mapple`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mapple`.`Usuario` (
  `correoUsuario` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(80) NOT NULL,
  `telefono` INT NOT NULL,
  `clave` VARCHAR(256) NOT NULL,
  `codDireccion` INT NOT NULL,
  PRIMARY KEY (`correoUsuario`, `codDireccion`),
  INDEX `fk_Usuario_Direccion1_idx` (`codDireccion` ASC),
  CONSTRAINT `fk_Usuario_Direccion1`
    FOREIGN KEY (`codDireccion`)
    REFERENCES `Mapple`.`Direccion` (`codDireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mapple`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mapple`.`Pedido` (
  `codPedido` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `importeTotal` VARCHAR(45) NOT NULL,
  `correoUsuario` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`codPedido`, `correoUsuario`),
  INDEX `fk_Pedido_Usuario1_idx` (`correoUsuario` ASC),
  CONSTRAINT `fk_Pedido_Usuario1`
    FOREIGN KEY (`correoUsuario`)
    REFERENCES `Mapple`.`Usuario` (`correoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mapple`.`LineaPedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mapple`.`LineaPedido` (
  `codLineaPedido` INT NOT NULL,
  `precioUnidad` DOUBLE NOT NULL,
  `cantidad` INT NOT NULL,
  `codPedido` INT NOT NULL,
  `codProducto` INT NOT NULL,
  PRIMARY KEY (`codLineaPedido`, `codPedido`, `codProducto`),
  INDEX `fk_LineaPedido_Pedido1_idx` (`codPedido` ASC),
  INDEX `fk_LineaPedido_Producto1_idx` (`codProducto` ASC),
  CONSTRAINT `fk_LineaPedido_Pedido1`
    FOREIGN KEY (`codPedido`)
    REFERENCES `Mapple`.`Pedido` (`codPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LineaPedido_Producto1`
    FOREIGN KEY (`codProducto`)
    REFERENCES `Mapple`.`Producto` (`codProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mapple`.`Idioma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mapple`.`Idioma` (
  `codIdioma` VARCHAR(2) NOT NULL,
  `nombreIdioma` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codIdioma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mapple`.`Producto_Idioma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mapple`.`Producto_Idioma` (
  `codProducto` INT NOT NULL,
  `codIdioma` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`codProducto`, `codIdioma`),
  INDEX `fk_Producto_Idioma_Producto1_idx` (`codProducto` ASC),
  INDEX `fk_Producto_Idioma_Idioma1_idx` (`codIdioma` ASC),
  CONSTRAINT `fk_Producto_Idioma_Producto1`
    FOREIGN KEY (`codProducto`)
    REFERENCES `Mapple`.`Producto` (`codProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Idioma_Idioma1`
    FOREIGN KEY (`codIdioma`)
    REFERENCES `Mapple`.`Idioma` (`codIdioma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mapple`.`Categoria_Idioma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mapple`.`Categoria_Idioma` (
  `codIdioma` VARCHAR(2) NOT NULL,
  `codCategoria` INT NOT NULL,
  PRIMARY KEY (`codIdioma`, `codCategoria`),
  INDEX `fk_Categoria_Idioma_Categoria1_idx` (`codCategoria` ASC),
  CONSTRAINT `fk_Categoria_Idioma_Idioma1`
    FOREIGN KEY (`codIdioma`)
    REFERENCES `Mapple`.`Idioma` (`codIdioma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Categoria_Idioma_Categoria1`
    FOREIGN KEY (`codCategoria`)
    REFERENCES `Mapple`.`Categoria` (`codCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
